spring:
  main:
    allow-bean-definition-overriding: on
  flyway:
    enabled: true
    schemas: public
    out-of-order: true
    url: jdbc:postgresql://localhost:5432/test
    password: 1
    driver-class-name: org.postgresql.Driver
    user: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/test
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        default_schema: public
        format_sql: true
        jdbc:
          batch_size: 10
        order_inserts: true
        order_updates: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: off
  data:
    rest:
        default-page-size: 100
        max-page-size: 1000
  jackson:
      serialization:
        FAIL_ON_UNWRAPPED_TYPE_IDENTIFIERS: false
  resources:
      add-mappings: false
  quartz:
    auto-startup: false
mvc:
  request-timeout: 180s

external-api:
  url: https://api.monobank.ua/bank/currency

using:
  spring:
    schedulerFactory: true





